/** Colloquial destination / city search aliases → catalog country name. */
export const SEARCH_ALIAS_PAIRS: readonly (readonly [string, string])[] = [
  ["bali", "Indonesia"],
  ["бали", "Indonesia"],
  ["lombok", "Indonesia"],
  ["ломбок", "Indonesia"],
  ["jakarta", "Indonesia"],
  ["джакарта", "Indonesia"],
  ["ubud", "Indonesia"],
  ["юбуд", "Indonesia"],
  ["denpasar", "Indonesia"],
  ["sumatra", "Indonesia"],
  ["суматра", "Indonesia"],
  ["java", "Indonesia"],
  ["ява", "Indonesia"],
  ["yogyakarta", "Indonesia"],
  ["джокьякарта", "Indonesia"],
  ["jogja", "Indonesia"],
  ["bandung", "Indonesia"],
  ["surabaya", "Indonesia"],
  ["medan", "Indonesia"],
  ["komodo", "Indonesia"],
  ["комодо", "Indonesia"],
  ["nusa penida", "Indonesia"],
  ["nusa dua", "Indonesia"],
  ["seminyak", "Indonesia"],
  ["canggu", "Indonesia"],
  ["borneo", "Indonesia"],
  ["калимантан", "Indonesia"],
  ["thailand", "Thailand"],
  ["таиланд", "Thailand"],
  ["тайланд", "Thailand"],
  ["phuket", "Thailand"],
  ["пхукет", "Thailand"],
  ["pattaya", "Thailand"],
  ["паттайя", "Thailand"],
  ["bangkok", "Thailand"],
  ["бангкок", "Thailand"],
  ["samui", "Thailand"],
  ["самуи", "Thailand"],
  ["koh samui", "Thailand"],
  ["ko samui", "Thailand"],
  ["krabi", "Thailand"],
  ["краби", "Thailand"],
  ["chiang mai", "Thailand"],
  ["чианг май", "Thailand"],
  ["hua hin", "Thailand"],
  ["koh phangan", "Thailand"],
  ["панган", "Thailand"],
  ["phi phi", "Thailand"],
  ["пипи", "Thailand"],
  ["ayutthaya", "Thailand"],
  ["koh lanta", "Thailand"],
  ["koh tao", "Thailand"],
  ["phangan", "Thailand"],
  ["uae", "United Arab Emirates"],
  ["оаэ", "United Arab Emirates"],
  ["dubai", "United Arab Emirates"],
  ["дубай", "United Arab Emirates"],
  ["abu dhabi", "United Arab Emirates"],
  ["абу даби", "United Arab Emirates"],
  ["sharjah", "United Arab Emirates"],
  ["шарджа", "United Arab Emirates"],
  ["ras al khaimah", "United Arab Emirates"],
  ["ajman", "United Arab Emirates"],
  ["fujairah", "United Arab Emirates"],
  ["usa", "United States of America"],
  ["us", "United States of America"],
  ["сша", "United States of America"],
  ["america", "United States of America"],
  ["америка", "United States of America"],
  ["new york", "United States of America"],
  ["нью йорк", "United States of America"],
  ["нью-йорк", "United States of America"],
  ["nyc", "United States of America"],
  ["manhattan", "United States of America"],
  ["манхэттен", "United States of America"],
  ["los angeles", "United States of America"],
  ["лос анджелес", "United States of America"],
  ["la", "United States of America"],
  ["california", "United States of America"],
  ["калифорния", "United States of America"],
  ["miami", "United States of America"],
  ["майами", "United States of America"],
  ["florida", "United States of America"],
  ["флорида", "United States of America"],
  ["hawaii", "United States of America"],
  ["гавайи", "United States of America"],
  ["гаваи", "United States of America"],
  ["las vegas", "United States of America"],
  ["vegas", "United States of America"],
  ["лас вегас", "United States of America"],
  ["san francisco", "United States of America"],
  ["сан франциско", "United States of America"],
  ["chicago", "United States of America"],
  ["чикаго", "United States of America"],
  ["boston", "United States of America"],
  ["washington", "United States of America"],
  ["seattle", "United States of America"],
  ["texas", "United States of America"],
  ["orlando", "United States of America"],
  ["honolulu", "United States of America"],
  ["san diego", "United States of America"],
  ["yellowstone", "United States of America"],
  ["grand canyon", "United States of America"],
  ["uk", "United Kingdom of Great Britain and Northern Ireland"],
  ["gb", "United Kingdom of Great Britain and Northern Ireland"],
  ["britain", "United Kingdom of Great Britain and Northern Ireland"],
  ["британия", "United Kingdom of Great Britain and Northern Ireland"],
  ["england", "United Kingdom of Great Britain and Northern Ireland"],
  ["англия", "United Kingdom of Great Britain and Northern Ireland"],
  ["london", "United Kingdom of Great Britain and Northern Ireland"],
  ["лондон", "United Kingdom of Great Britain and Northern Ireland"],
  ["scotland", "United Kingdom of Great Britain and Northern Ireland"],
  ["шотландия", "United Kingdom of Great Britain and Northern Ireland"],
  ["edinburgh", "United Kingdom of Great Britain and Northern Ireland"],
  ["wales", "United Kingdom of Great Britain and Northern Ireland"],
  ["уэльс", "United Kingdom of Great Britain and Northern Ireland"],
  ["manchester", "United Kingdom of Great Britain and Northern Ireland"],
  ["liverpool", "United Kingdom of Great Britain and Northern Ireland"],
  ["oxford", "United Kingdom of Great Britain and Northern Ireland"],
  ["cambridge", "United Kingdom of Great Britain and Northern Ireland"],
  ["birmingham", "United Kingdom of Great Britain and Northern Ireland"],
  ["glasgow", "United Kingdom of Great Britain and Northern Ireland"],
  ["france", "France"],
  ["франция", "France"],
  ["paris", "France"],
  ["париж", "France"],
  ["nice", "France"],
  ["ницца", "France"],
  ["cannes", "France"],
  ["канны", "France"],
  ["lyon", "France"],
  ["лион", "France"],
  ["marseille", "France"],
  ["марсель", "France"],
  ["provence", "France"],
  ["прованс", "France"],
  ["bordeaux", "France"],
  ["бордо", "France"],
  ["normandy", "France"],
  ["нормандия", "France"],
  ["corsica", "France"],
  ["корсика", "France"],
  ["strasbourg", "France"],
  ["french riviera", "France"],
  ["лазурный берег", "France"],
  ["chamonix", "France"],
  ["шамони", "France"],
  ["italy", "Italy"],
  ["италия", "Italy"],
  ["rome", "Italy"],
  ["рим", "Italy"],
  ["roma", "Italy"],
  ["milan", "Italy"],
  ["милан", "Italy"],
  ["milano", "Italy"],
  ["venice", "Italy"],
  ["венеция", "Italy"],
  ["venezia", "Italy"],
  ["florence", "Italy"],
  ["флоренция", "Italy"],
  ["firenze", "Italy"],
  ["naples", "Italy"],
  ["неаполь", "Italy"],
  ["napoli", "Italy"],
  ["sicily", "Italy"],
  ["сицилия", "Italy"],
  ["sardinia", "Italy"],
  ["сардиния", "Italy"],
  ["amalfi", "Italy"],
  ["амальфи", "Italy"],
  ["amalfi coast", "Italy"],
  ["cinque terre", "Italy"],
  ["tuscany", "Italy"],
  ["тоскана", "Italy"],
  ["turin", "Italy"],
  ["bologna", "Italy"],
  ["verona", "Italy"],
  ["lake como", "Italy"],
  ["комо", "Italy"],
  ["pisa", "Italy"],
  ["пиза", "Italy"],
  ["capri", "Italy"],
  ["капри", "Italy"],
  ["positano", "Italy"],
  ["позитано", "Italy"],
  ["rimini", "Italy"],
  ["римини", "Italy"],
  ["spain", "Spain"],
  ["испания", "Spain"],
  ["barcelona", "Spain"],
  ["барселона", "Spain"],
  ["madrid", "Spain"],
  ["мадрид", "Spain"],
  ["ibiza", "Spain"],
  ["ибица", "Spain"],
  ["mallorca", "Spain"],
  ["майорка", "Spain"],
  ["majorca", "Spain"],
  ["canaries", "Spain"],
  ["канары", "Spain"],
  ["tenerife", "Spain"],
  ["тенерифе", "Spain"],
  ["gran canaria", "Spain"],
  ["lanzarote", "Spain"],
  ["valencia", "Spain"],
  ["валенсия", "Spain"],
  ["seville", "Spain"],
  ["севилья", "Spain"],
  ["malaga", "Spain"],
  ["малага", "Spain"],
  ["marbella", "Spain"],
  ["марбелья", "Spain"],
  ["costa brava", "Spain"],
  ["costa del sol", "Spain"],
  ["коста браво", "Spain"],
  ["bilbao", "Spain"],
  ["san sebastian", "Spain"],
  ["palma", "Spain"],
  ["greece", "Greece"],
  ["греция", "Greece"],
  ["athens", "Greece"],
  ["афины", "Greece"],
  ["santorini", "Greece"],
  ["санторини", "Greece"],
  ["mykonos", "Greece"],
  ["миконос", "Greece"],
  ["crete", "Greece"],
  ["крит", "Greece"],
  ["rhodes", "Greece"],
  ["родос", "Greece"],
  ["corfu", "Greece"],
  ["корфу", "Greece"],
  ["zakynthos", "Greece"],
  ["закинф", "Greece"],
  ["thessaloniki", "Greece"],
  ["салоники", "Greece"],
  ["paros", "Greece"],
  ["naxos", "Greece"],
  ["kos", "Greece"],
  ["halkidiki", "Greece"],
  ["халкидики", "Greece"],
  ["turkey", "Turkey"],
  ["турция", "Turkey"],
  ["istanbul", "Turkey"],
  ["стамбул", "Turkey"],
  ["antalya", "Turkey"],
  ["анталия", "Turkey"],
  ["bodrum", "Turkey"],
  ["бодрум", "Turkey"],
  ["cappadocia", "Turkey"],
  ["каппадокия", "Turkey"],
  ["izmir", "Turkey"],
  ["измир", "Turkey"],
  ["ankara", "Turkey"],
  ["анкара", "Turkey"],
  ["kemer", "Turkey"],
  ["кемер", "Turkey"],
  ["belek", "Turkey"],
  ["белек", "Turkey"],
  ["side", "Turkey"],
  ["сиде", "Turkey"],
  ["alanya", "Turkey"],
  ["аланья", "Turkey"],
  ["fethiye", "Turkey"],
  ["фетхие", "Turkey"],
  ["marmaris", "Turkey"],
  ["мармарис", "Turkey"],
  ["kusadasi", "Turkey"],
  ["кушадасы", "Turkey"],
  ["pamukkale", "Turkey"],
  ["памуккале", "Turkey"],
  ["trabzon", "Turkey"],
  ["трабзон", "Turkey"],
  ["egypt", "Egypt"],
  ["египет", "Egypt"],
  ["cairo", "Egypt"],
  ["каир", "Egypt"],
  ["hurghada", "Egypt"],
  ["хургада", "Egypt"],
  ["sharm", "Egypt"],
  ["шарм", "Egypt"],
  ["sharm el sheikh", "Egypt"],
  ["шарм эль шейх", "Egypt"],
  ["luxor", "Egypt"],
  ["луксор", "Egypt"],
  ["aswan", "Egypt"],
  ["асуан", "Egypt"],
  ["dahab", "Egypt"],
  ["дахаб", "Egypt"],
  ["marsa alam", "Egypt"],
  ["марса алам", "Egypt"],
  ["alexandria", "Egypt"],
  ["александрия", "Egypt"],
  ["india", "India"],
  ["индия", "India"],
  ["goa", "India"],
  ["гоа", "India"],
  ["mumbai", "India"],
  ["мумбаи", "India"],
  ["бомбей", "India"],
  ["bombay", "India"],
  ["delhi", "India"],
  ["дели", "India"],
  ["new delhi", "India"],
  ["jaipur", "India"],
  ["джайпур", "India"],
  ["kerala", "India"],
  ["керала", "India"],
  ["agra", "India"],
  ["агра", "India"],
  ["taj mahal", "India"],
  ["rajasthan", "India"],
  ["раджастан", "India"],
  ["varanasi", "India"],
  ["варанаси", "India"],
  ["bangalore", "India"],
  ["бангалор", "India"],
  ["chennai", "India"],
  ["чennai", "India"],
  ["kolkata", "India"],
  ["calcutta", "India"],
  ["калькутта", "India"],
  ["udaipur", "India"],
  ["удаипур", "India"],
  ["manali", "India"],
  ["манали", "India"],
  ["shimla", "India"],
  ["rishikesh", "India"],
  ["ришикеш", "India"],
  ["vietnam", "Viet Nam"],
  ["вьетнам", "Viet Nam"],
  ["hanoi", "Viet Nam"],
  ["ханой", "Viet Nam"],
  ["saigon", "Viet Nam"],
  ["сайгон", "Viet Nam"],
  ["ho chi minh", "Viet Nam"],
  ["хошимин", "Viet Nam"],
  ["hcmc", "Viet Nam"],
  ["da nang", "Viet Nam"],
  ["дананг", "Viet Nam"],
  ["nha trang", "Viet Nam"],
  ["нячанг", "Viet Nam"],
  ["phu quoc", "Viet Nam"],
  ["фукуок", "Viet Nam"],
  ["hoi an", "Viet Nam"],
  ["хойан", "Viet Nam"],
  ["halong", "Viet Nam"],
  ["халонг", "Viet Nam"],
  ["halong bay", "Viet Nam"],
  ["sapa", "Viet Nam"],
  ["сапа", "Viet Nam"],
  ["mui ne", "Viet Nam"],
  ["dalat", "Viet Nam"],
  ["hue", "Viet Nam"],
  ["хюэ", "Viet Nam"],
  ["japan", "Japan"],
  ["япония", "Japan"],
  ["tokyo", "Japan"],
  ["токио", "Japan"],
  ["osaka", "Japan"],
  ["осака", "Japan"],
  ["kyoto", "Japan"],
  ["киото", "Japan"],
  ["okinawa", "Japan"],
  ["окинава", "Japan"],
  ["hokkaido", "Japan"],
  ["хоккайдо", "Japan"],
  ["hiroshima", "Japan"],
  ["хиросима", "Japan"],
  ["nara", "Japan"],
  ["нара", "Japan"],
  ["fuji", "Japan"],
  ["фудзи", "Japan"],
  ["mount fuji", "Japan"],
  ["sapporo", "Japan"],
  ["саппоро", "Japan"],
  ["yokohama", "Japan"],
  ["nagoya", "Japan"],
  ["нагоя", "Japan"],
  ["fukuoka", "Japan"],
  ["фукуока", "Japan"],
  ["korea", "Korea, Republic of"],
  ["south korea", "Korea, Republic of"],
  ["южная корея", "Korea, Republic of"],
  ["корея", "Korea, Republic of"],
  ["seoul", "Korea, Republic of"],
  ["сеул", "Korea, Republic of"],
  ["busan", "Korea, Republic of"],
  ["пусан", "Korea, Republic of"],
  ["jeju", "Korea, Republic of"],
  ["чеджу", "Korea, Republic of"],
  ["jeju island", "Korea, Republic of"],
  ["incheon", "Korea, Republic of"],
  ["china", "China"],
  ["китай", "China"],
  ["beijing", "China"],
  ["пекин", "China"],
  ["shanghai", "China"],
  ["шанхай", "China"],
  ["guangzhou", "China"],
  ["гуанчжоу", "China"],
  ["shenzhen", "China"],
  ["шэньчжэнь", "China"],
  ["chengdu", "China"],
  ["чэнду", "China"],
  ["xian", "China"],
  ["сиань", "China"],
  ["hangzhou", "China"],
  ["ханчжоу", "China"],
  ["guilin", "China"],
  ["гуйлинь", "China"],
  ["zhangjiajie", "China"],
  ["sanya", "China"],
  ["санья", "China"],
  ["harbin", "China"],
  ["харбин", "China"],
  ["hong kong", "Hong Kong"],
  ["гонконг", "Hong Kong"],
  ["hk", "Hong Kong"],
  ["macau", "Macao"],
  ["macao", "Macao"],
  ["макао", "Macao"],
  ["taiwan", "Taiwan, Province of China"],
  ["тайвань", "Taiwan, Province of China"],
  ["taipei", "Taiwan, Province of China"],
  ["тайбэй", "Taiwan, Province of China"],
  ["malaysia", "Malaysia"],
  ["малайзия", "Malaysia"],
  ["kuala lumpur", "Malaysia"],
  ["куала лумпур", "Malaysia"],
  ["kl", "Malaysia"],
  ["langkawi", "Malaysia"],
  ["лангкави", "Malaysia"],
  ["penang", "Malaysia"],
  ["пенанг", "Malaysia"],
  ["kota kinabalu", "Malaysia"],
  ["singapore", "Singapore"],
  ["сингапур", "Singapore"],
  ["сингапор", "Singapore"],
  ["philippines", "Philippines"],
  ["филиппины", "Philippines"],
  ["manila", "Philippines"],
  ["манила", "Philippines"],
  ["cebu", "Philippines"],
  ["себу", "Philippines"],
  ["boracay", "Philippines"],
  ["боракай", "Philippines"],
  ["palawan", "Philippines"],
  ["палаван", "Philippines"],
  ["el nido", "Philippines"],
  ["siargao", "Philippines"],
  ["maldives", "Maldives"],
  ["мальдивы", "Maldives"],
  ["male", "Maldives"],
  ["sri lanka", "Sri Lanka"],
  ["шри ланка", "Sri Lanka"],
  ["шри-ланка", "Sri Lanka"],
  ["colombo", "Sri Lanka"],
  ["коломбо", "Sri Lanka"],
  ["nepal", "Nepal"],
  ["непал", "Nepal"],
  ["kathmandu", "Nepal"],
  ["катманду", "Nepal"],
  ["everest", "Nepal"],
  ["эверест", "Nepal"],
  ["cambodia", "Cambodia"],
  ["камбоджа", "Cambodia"],
  ["siem reap", "Cambodia"],
  ["сиемреап", "Cambodia"],
  ["angkor", "Cambodia"],
  ["ангкор", "Cambodia"],
  ["phnom penh", "Cambodia"],
  ["laos", "Lao People's Democratic Republic"],
  ["лаос", "Lao People's Democratic Republic"],
  ["vientiane", "Lao People's Democratic Republic"],
  ["luang prabang", "Lao People's Democratic Republic"],
  ["mexico", "Mexico"],
  ["мексика", "Mexico"],
  ["cancun", "Mexico"],
  ["канкун", "Mexico"],
  ["playa del carmen", "Mexico"],
  ["плая дель кармен", "Mexico"],
  ["tulum", "Mexico"],
  ["турум", "Mexico"],
  ["los cabos", "Mexico"],
  ["cabo", "Mexico"],
  ["кабо", "Mexico"],
  ["puerto vallarta", "Mexico"],
  ["mexico city", "Mexico"],
  ["cdmx", "Mexico"],
  ["riviera maya", "Mexico"],
  ["cozumel", "Mexico"],
  ["oaxaca", "Mexico"],
  ["dominican republic", "Dominican Republic"],
  ["доминикана", "Dominican Republic"],
  ["punta cana", "Dominican Republic"],
  ["пунта кана", "Dominican Republic"],
  ["bavaro", "Dominican Republic"],
  ["cuba", "Cuba"],
  ["куба", "Cuba"],
  ["havana", "Cuba"],
  ["гавана", "Cuba"],
  ["varadero", "Cuba"],
  ["вардеро", "Cuba"],
  ["jamaica", "Jamaica"],
  ["ямайка", "Jamaica"],
  ["montego bay", "Jamaica"],
  ["bahamas", "Bahamas"],
  ["багамы", "Bahamas"],
  ["nassau", "Bahamas"],
  ["costa rica", "Costa Rica"],
  ["коста рика", "Costa Rica"],
  ["panama", "Panama"],
  ["панама", "Panama"],
  ["panama city", "Panama"],
  ["curacao", "Curaçao"],
  ["кюрасао", "Curaçao"],
  ["colombia", "Colombia"],
  ["колумбия", "Colombia"],
  ["cartagena", "Colombia"],
  ["картахена", "Colombia"],
  ["medellin", "Colombia"],
  ["медельин", "Colombia"],
  ["bogota", "Colombia"],
  ["богота", "Colombia"],
  ["brazil", "Brazil"],
  ["бразилия", "Brazil"],
  ["rio", "Brazil"],
  ["рио", "Brazil"],
  ["rio de janeiro", "Brazil"],
  ["sao paulo", "Brazil"],
  ["сан паулу", "Brazil"],
  ["salvador", "Brazil"],
  ["argentina", "Argentina"],
  ["аргентина", "Argentina"],
  ["buenos aires", "Argentina"],
  ["буэнос айрес", "Argentina"],
  ["patagonia", "Argentina"],
  ["патагония", "Argentina"],
  ["bariloche", "Argentina"],
  ["peru", "Peru"],
  ["перу", "Peru"],
  ["machu picchu", "Peru"],
  ["мачу пикчу", "Peru"],
  ["cusco", "Peru"],
  ["куско", "Peru"],
  ["lima", "Peru"],
  ["лима", "Peru"],
  ["chile", "Chile"],
  ["чили", "Chile"],
  ["santiago", "Chile"],
  ["ecuador", "Ecuador"],
  ["эквадор", "Ecuador"],
  ["galapagos", "Ecuador"],
  ["галапагосы", "Ecuador"],
  ["uruguay", "Uruguay"],
  ["уругвай", "Uruguay"],
  ["montevideo", "Uruguay"],
  ["paraguay", "Paraguay"],
  ["парагвай", "Paraguay"],
  ["morocco", "Morocco"],
  ["марокко", "Morocco"],
  ["marrakech", "Morocco"],
  ["марракеш", "Morocco"],
  ["marrakesh", "Morocco"],
  ["casablanca", "Morocco"],
  ["касабланка", "Morocco"],
  ["fez", "Morocco"],
  ["фес", "Morocco"],
  ["tangier", "Morocco"],
  ["tunisia", "Tunisia"],
  ["тунис", "Tunisia"],
  ["djerba", "Tunisia"],
  ["джерба", "Tunisia"],
  ["south africa", "South Africa"],
  ["юар", "South Africa"],
  ["cape town", "South Africa"],
  ["кейптаун", "South Africa"],
  ["johannesburg", "South Africa"],
  ["kenya", "Kenya"],
  ["кения", "Kenya"],
  ["nairobi", "Kenya"],
  ["найроби", "Kenya"],
  ["masai mara", "Kenya"],
  ["safari", "Kenya"],
  ["tanzania", "Tanzania, United Republic of"],
  ["танзания", "Tanzania, United Republic of"],
  ["zanzibar", "Tanzania, United Republic of"],
  ["занзибар", "Tanzania, United Republic of"],
  ["serengeti", "Tanzania, United Republic of"],
  ["kilimanjaro", "Tanzania, United Republic of"],
  ["mauritius", "Mauritius"],
  ["маврикий", "Mauritius"],
  ["seychelles", "Seychelles"],
  ["сейшелы", "Seychelles"],
  ["madagascar", "Madagascar"],
  ["мадагаскар", "Madagascar"],
  ["nigeria", "Nigeria"],
  ["нигерия", "Nigeria"],
  ["lagos", "Nigeria"],
  ["ghana", "Ghana"],
  ["гана", "Ghana"],
  ["ethiopia", "Ethiopia"],
  ["эфиопия", "Ethiopia"],
  ["rwanda", "Rwanda"],
  ["руанда", "Rwanda"],
  ["uganda", "Uganda"],
  ["уганда", "Uganda"],
  ["senegal", "Senegal"],
  ["сенегал", "Senegal"],
  ["gabon", "Gabon"],
  ["габон", "Gabon"],
  ["israel", "Israel"],
  ["израиль", "Israel"],
  ["tel aviv", "Israel"],
  ["тель авив", "Israel"],
  ["jerusalem", "Israel"],
  ["иерусалим", "Israel"],
  ["dead sea", "Israel"],
  ["jordan", "Jordan"],
  ["иордания", "Jordan"],
  ["petra", "Jordan"],
  ["петра", "Jordan"],
  ["amman", "Jordan"],
  ["амман", "Jordan"],
  ["saudi arabia", "Saudi Arabia"],
  ["саудовская аравия", "Saudi Arabia"],
  ["riyadh", "Saudi Arabia"],
  ["jeddah", "Saudi Arabia"],
  ["джедда", "Saudi Arabia"],
  ["mecca", "Saudi Arabia"],
  ["мекка", "Saudi Arabia"],
  ["medina", "Saudi Arabia"],
  ["медина", "Saudi Arabia"],
  ["qatar", "Qatar"],
  ["катар", "Qatar"],
  ["doha", "Qatar"],
  ["доха", "Qatar"],
  ["oman", "Oman"],
  ["оман", "Oman"],
  ["muscat", "Oman"],
  ["мускат", "Oman"],
  ["bahrain", "Bahrain"],
  ["бахрейн", "Bahrain"],
  ["kuwait", "Kuwait"],
  ["кувейт", "Kuwait"],
  ["iran", "Iran (Islamic Republic of)"],
  ["иран", "Iran (Islamic Republic of)"],
  ["tehran", "Iran (Islamic Republic of)"],
  ["тегеран", "Iran (Islamic Republic of)"],
  ["iraq", "Iraq"],
  ["ирак", "Iraq"],
  ["baghdad", "Iraq"],
  ["australia", "Australia"],
  ["австралия", "Australia"],
  ["sydney", "Australia"],
  ["сидней", "Australia"],
  ["melbourne", "Australia"],
  ["мельбурн", "Australia"],
  ["gold coast", "Australia"],
  ["голд коуст", "Australia"],
  ["perth", "Australia"],
  ["brisbane", "Australia"],
  ["брисбен", "Australia"],
  ["cairns", "Australia"],
  ["кэрнс", "Australia"],
  ["great barrier reef", "Australia"],
  ["new zealand", "New Zealand"],
  ["новая зеландия", "New Zealand"],
  ["nz", "New Zealand"],
  ["auckland", "New Zealand"],
  ["окленд", "New Zealand"],
  ["queenstown", "New Zealand"],
  ["квинстаун", "New Zealand"],
  ["fiji", "Fiji"],
  ["фиджи", "Fiji"],
  ["tahiti", "French Polynesia"],
  ["таити", "French Polynesia"],
  ["bora bora", "French Polynesia"],
  ["бора бора", "French Polynesia"],
  ["moorea", "French Polynesia"],
  ["guam", "Guam"],
  ["гуам", "Guam"],
  ["portugal", "Portugal"],
  ["португалия", "Portugal"],
  ["lisbon", "Portugal"],
  ["лиссабон", "Portugal"],
  ["porto", "Portugal"],
  ["порту", "Portugal"],
  ["algarve", "Portugal"],
  ["алгарве", "Portugal"],
  ["madeira", "Portugal"],
  ["мадейра", "Portugal"],
  ["netherlands", "Netherlands"],
  ["нидерланды", "Netherlands"],
  ["holland", "Netherlands"],
  ["голландия", "Netherlands"],
  ["amsterdam", "Netherlands"],
  ["амстердам", "Netherlands"],
  ["belgium", "Belgium"],
  ["бельгия", "Belgium"],
  ["brussels", "Belgium"],
  ["брюссель", "Belgium"],
  ["bruges", "Belgium"],
  ["брюгге", "Belgium"],
  ["germany", "Germany"],
  ["германия", "Germany"],
  ["berlin", "Germany"],
  ["берлин", "Germany"],
  ["munich", "Germany"],
  ["мюнхен", "Germany"],
  ["frankfurt", "Germany"],
  ["франкфурт", "Germany"],
  ["hamburg", "Germany"],
  ["гамбург", "Germany"],
  ["cologne", "Germany"],
  ["кёльн", "Germany"],
  ["bavaria", "Germany"],
  ["бавария", "Germany"],
  ["dresden", "Germany"],
  ["дрезден", "Germany"],
  ["austria", "Austria"],
  ["австрия", "Austria"],
  ["vienna", "Austria"],
  ["вена", "Austria"],
  ["salzburg", "Austria"],
  ["зальцбург", "Austria"],
  ["innsbruck", "Austria"],
  ["инсбрук", "Austria"],
  ["switzerland", "Switzerland"],
  ["швейцария", "Switzerland"],
  ["zurich", "Switzerland"],
  ["цюрих", "Switzerland"],
  ["geneva", "Switzerland"],
  ["женева", "Switzerland"],
  ["interlaken", "Switzerland"],
  ["интерлакен", "Switzerland"],
  ["zermatt", "Switzerland"],
  ["церматт", "Switzerland"],
  ["czechia", "Czechia"],
  ["czech republic", "Czechia"],
  ["чехия", "Czechia"],
  ["prague", "Czechia"],
  ["прага", "Czechia"],
  ["praha", "Czechia"],
  ["hungary", "Hungary"],
  ["венгрия", "Hungary"],
  ["budapest", "Hungary"],
  ["будапешт", "Hungary"],
  ["poland", "Poland"],
  ["польша", "Poland"],
  ["warsaw", "Poland"],
  ["варшава", "Poland"],
  ["krakow", "Poland"],
  ["краков", "Poland"],
  ["gdansk", "Poland"],
  ["данциг", "Poland"],
  ["croatia", "Croatia"],
  ["хорватия", "Croatia"],
  ["dubrovnik", "Croatia"],
  ["дубровник", "Croatia"],
  ["split", "Croatia"],
  ["сплит", "Croatia"],
  ["zagreb", "Croatia"],
  ["загреб", "Croatia"],
  ["hvar", "Croatia"],
  ["хвар", "Croatia"],
  ["montenegro", "Montenegro"],
  ["черногория", "Montenegro"],
  ["budva", "Montenegro"],
  ["будва", "Montenegro"],
  ["kotor", "Montenegro"],
  ["котор", "Montenegro"],
  ["serbia", "Serbia"],
  ["сербия", "Serbia"],
  ["belgrade", "Serbia"],
  ["белград", "Serbia"],
  ["bulgaria", "Bulgaria"],
  ["болгария", "Bulgaria"],
  ["sofia", "Bulgaria"],
  ["софия", "Bulgaria"],
  ["varna", "Bulgaria"],
  ["варна", "Bulgaria"],
  ["romania", "Romania"],
  ["румыния", "Romania"],
  ["bucharest", "Romania"],
  ["бухарест", "Romania"],
  ["transylvania", "Romania"],
  ["трансильвания", "Romania"],
  ["iceland", "Iceland"],
  ["исландия", "Iceland"],
  ["reykjavik", "Iceland"],
  ["рейкьявик", "Iceland"],
  ["ireland", "Ireland"],
  ["ирландия", "Ireland"],
  ["dublin", "Ireland"],
  ["дублин", "Ireland"],
  ["norway", "Norway"],
  ["норвегия", "Norway"],
  ["oslo", "Norway"],
  ["осло", "Norway"],
  ["bergen", "Norway"],
  ["бeрген", "Norway"],
  ["fjords", "Norway"],
  ["фьорды", "Norway"],
  ["sweden", "Sweden"],
  ["швеция", "Sweden"],
  ["stockholm", "Sweden"],
  ["стокгольм", "Sweden"],
  ["denmark", "Denmark"],
  ["дания", "Denmark"],
  ["copenhagen", "Denmark"],
  ["копенгаген", "Denmark"],
  ["finland", "Finland"],
  ["финляндия", "Finland"],
  ["helsinki", "Finland"],
  ["хельсинки", "Finland"],
  ["lapland", "Finland"],
  ["лапландия", "Finland"],
  ["estonia", "Estonia"],
  ["эстония", "Estonia"],
  ["tallinn", "Estonia"],
  ["таллин", "Estonia"],
  ["latvia", "Latvia"],
  ["латвия", "Latvia"],
  ["riga", "Latvia"],
  ["рига", "Latvia"],
  ["lithuania", "Lithuania"],
  ["литва", "Lithuania"],
  ["vilnius", "Lithuania"],
  ["вильнюс", "Lithuania"],
  ["cyprus", "Cyprus"],
  ["кипр", "Cyprus"],
  ["ayia napa", "Cyprus"],
  ["айя напа", "Cyprus"],
  ["limassol", "Cyprus"],
  ["лимассол", "Cyprus"],
  ["paphos", "Cyprus"],
  ["пафос", "Cyprus"],
  ["malta", "Malta"],
  ["мальта", "Malta"],
  ["valletta", "Malta"],
  ["валлетта", "Malta"],
  ["slovenia", "Slovenia"],
  ["словения", "Slovenia"],
  ["ljubljana", "Slovenia"],
  ["slovakia", "Slovakia"],
  ["словакия", "Slovakia"],
  ["bratislava", "Slovakia"],
  ["luxembourg", "Luxembourg"],
  ["люксембург", "Luxembourg"],
  ["liechtenstein", "Liechtenstein"],
  ["лихтенштейн", "Liechtenstein"],
  ["monaco", "Monaco"],
  ["монако", "Monaco"],
  ["andorra", "Andorra"],
  ["андорра", "Andorra"],
  ["albania", "Albania"],
  ["албания", "Albania"],
  ["tirana", "Albania"],
  ["north macedonia", "North Macedonia"],
  ["македония", "North Macedonia"],
  ["skopje", "North Macedonia"],
  ["bosnia", "Bosnia and Herzegovina"],
  ["босния", "Bosnia and Herzegovina"],
  ["sarajevo", "Bosnia and Herzegovina"],
  ["moldova", "Moldova, Republic of"],
  ["молдова", "Moldova, Republic of"],
  ["chisinau", "Moldova, Republic of"],
  ["кишинев", "Moldova, Republic of"],
  ["belarus", "Belarus"],
  ["беларусь", "Belarus"],
  ["белоруссия", "Belarus"],
  ["minsk", "Belarus"],
  ["минск", "Belarus"],
  ["russia", "Russia"],
  ["россия", "Russia"],
  ["moscow", "Russia"],
  ["москва", "Russia"],
  ["msk", "Russia"],
  ["spb", "Russia"],
  ["питер", "Russia"],
  ["saint petersburg", "Russia"],
  ["санкт-петербург", "Russia"],
  ["санкт петербург", "Russia"],
  ["sochi", "Russia"],
  ["сочи", "Russia"],
  ["kazan", "Russia"],
  ["казань", "Russia"],
  ["krasnodar", "Russia"],
  ["крым", "Russia"],
  ["crimea", "Russia"],
  ["ukraine", "Ukraine"],
  ["украина", "Ukraine"],
  ["kyiv", "Ukraine"],
  ["kiev", "Ukraine"],
  ["киев", "Ukraine"],
  ["lviv", "Ukraine"],
  ["львов", "Ukraine"],
  ["lvov", "Ukraine"],
  ["odesa", "Ukraine"],
  ["одесса", "Ukraine"],
  ["odessa", "Ukraine"],
  ["georgia", "Georgia"],
  ["грузия", "Georgia"],
  ["tbilisi", "Georgia"],
  ["тбилиси", "Georgia"],
  ["batumi", "Georgia"],
  ["батуми", "Georgia"],
  ["armenia", "Armenia"],
  ["армения", "Armenia"],
  ["yerevan", "Armenia"],
  ["ереван", "Armenia"],
  ["azerbaijan", "Azerbaijan"],
  ["азербайджан", "Azerbaijan"],
  ["baku", "Azerbaijan"],
  ["баку", "Azerbaijan"],
  ["kazakhstan", "Kazakhstan"],
  ["казахстан", "Kazakhstan"],
  ["almaty", "Kazakhstan"],
  ["алматы", "Kazakhstan"],
  ["astana", "Kazakhstan"],
  ["астана", "Kazakhstan"],
  ["uzbekistan", "Uzbekistan"],
  ["узбекистан", "Uzbekistan"],
  ["tashkent", "Uzbekistan"],
  ["ташкент", "Uzbekistan"],
  ["samarkand", "Uzbekistan"],
  ["самарканд", "Uzbekistan"],
  ["bukhara", "Uzbekistan"],
  ["бухара", "Uzbekistan"],
  ["kyrgyzstan", "Kyrgyzstan"],
  ["киргизия", "Kyrgyzstan"],
  ["кыргызстан", "Kyrgyzstan"],
  ["bishkek", "Kyrgyzstan"],
  ["issyk kul", "Kyrgyzstan"],
  ["иссык-куль", "Kyrgyzstan"],
  ["tajikistan", "Tajikistan"],
  ["таджикистан", "Tajikistan"],
  ["dushanbe", "Tajikistan"],
  ["mongolia", "Mongolia"],
  ["монголия", "Mongolia"],
  ["ulaanbaatar", "Mongolia"],
  ["улан батор", "Mongolia"],
  ["canada", "Canada"],
  ["канада", "Canada"],
  ["toronto", "Canada"],
  ["торонто", "Canada"],
  ["vancouver", "Canada"],
  ["ванкувер", "Canada"],
  ["montreal", "Canada"],
  ["монреаль", "Canada"],
  ["banff", "Canada"],
  ["банф", "Canada"],
  ["quebec", "Canada"],
  ["квебек", "Canada"],
  ["pakistan", "Pakistan"],
  ["пакистан", "Pakistan"],
  ["karachi", "Pakistan"],
  ["lahore", "Pakistan"],
  ["islamabad", "Pakistan"],
  ["bangladesh", "Bangladesh"],
  ["бангладеш", "Bangladesh"],
  ["dhaka", "Bangladesh"],
  ["afghanistan", "Afghanistan"],
  ["афганистан", "Afghanistan"],
  ["kabul", "Afghanistan"],
  ["algeria", "Algeria"],
  ["алжир", "Algeria"],
  ["algiers", "Algeria"],
  ["benin", "Benin"],
  ["cameroon", "Cameroon"],
  ["камерун", "Cameroon"],
  ["chad", "Chad"],
  ["чад", "Chad"],
  ["congo", "Congo"],
  ["конго", "Congo"],
  ["drc", "Congo, Democratic Republic of the"],
  ["guyana", "Guyana"],
  ["гайана", "Guyana"],
  ["guatemala", "Guatemala"],
  ["гватемала", "Guatemala"],
  ["honduras", "Honduras"],
  ["гондурас", "Honduras"],
  ["nicaragua", "Nicaragua"],
  ["никарагуа", "Nicaragua"],
  ["niger", "Niger"],
  ["нигер", "Niger"],
  ["suriname", "Suriname"],
  ["суринам", "Suriname"],
  ["sudan", "Sudan"],
  ["судан", "Sudan"],
  ["mauritania", "Mauritania"],
  ["мавритания", "Mauritania"],
  ["mozambique", "Mozambique"],
  ["мозамбик", "Mozambique"],
  ["malawi", "Malawi"],
  ["малави", "Malawi"],
  ["faroe", "Faroe Islands"],
  ["фареры", "Faroe Islands"],
  ["gibraltar", "Gibraltar"],
  ["гибралтар", "Gibraltar"],
  ["bermuda", "Bermuda"],
  ["бермуды", "Bermuda"],
  ["cayman", "Cayman Islands"],
  ["кайманы", "Cayman Islands"],
  ["cayman islands", "Cayman Islands"],
  ["turks and caicos", "Turks and Caicos Islands"],
  ["тёркс", "Turks and Caicos Islands"],
  ["virgin islands", "Virgin Islands (British)"],
  ["бви", "Virgin Islands (British)"],
  ["puerto rico", "Puerto Rico"],
  ["пуэрто рико", "Puerto Rico"],
  ["martinique", "Martinique"],
  ["мартиника", "Martinique"],
  ["guadeloupe", "Guadeloupe"],
  ["гваделупа", "Guadeloupe"],
  ["reunion", "Réunion"],
  ["реюньон", "Réunion"],
  ["french guiana", "French Guiana"],
  ["гвиана", "French Guiana"],
  ["sint maarten", "Sint Maarten (Dutch part)"],
  ["синт-мартен", "Sint Maarten (Dutch part)"],
  ["bonaire", "Bonaire, Sint Eustatius and Saba"],
  ["бонэйр", "Bonaire, Sint Eustatius and Saba"],
  ["montserrat", "Montserrat"],
  ["anguilla", "Anguilla"],
  ["ангуилья", "Anguilla"],
  ["antigua", "Antigua and Barbuda"],
  ["barbados", "Barbados"],
  ["барбадос", "Barbados"],
  ["grenada", "Grenada"],
  ["гренада", "Grenada"],
  ["dominica", "Dominica"],
  ["доминика", "Dominica"],
  ["st lucia", "Saint Lucia"],
  ["сент-люсия", "Saint Lucia"],
  ["st kitts", "Saint Kitts and Nevis"],
  ["trinidad", "Trinidad and Tobago"],
  ["тринидад", "Trinidad and Tobago"],
  ["el salvador", "El Salvador"],
  ["сальвадор", "El Salvador"],
  ["venezuela", "Venezuela (Bolivarian Republic of)"],
  ["венесуэла", "Venezuela (Bolivarian Republic of)"],
  ["caracas", "Venezuela (Bolivarian Republic of)"],
  ["bolivia", "Bolivia (Plurinational State of)"],
  ["боливия", "Bolivia (Plurinational State of)"],
  ["la paz", "Bolivia (Plurinational State of)"],
  ["cabo verde", "Cabo Verde"],
  ["кабо верде", "Cabo Verde"],
  ["ivory coast", "Côte d'Ivoire"],
  ["кот дивуар", "Côte d'Ivoire"],
  ["cote divoire", "Côte d'Ivoire"],
] as const;

export function aliasesByCountry(): Map<string, string[]> {
  const m = new Map<string, string[]>();
  for (const [alias, country] of SEARCH_ALIAS_PAIRS) {
    let list = m.get(country);
    if (!list) { list = []; m.set(country, list); }
    list.push(alias);
  }
  return m;
}